#+TITLE: Simulating temperature programmed desorption of oxygen on Pt(111) using DFT derived coverage dependent desorption barriers
#+OPTIONS: toc:nil author:nil

#+LaTeX_CLASS: svjour3
#+latex_header: \usepackage[utf8]{inputenc}
#+latex_header: \usepackage{fixltx2e}
#+latex_header: \usepackage{url}
#+latex_header: \usepackage{graphicx}
#+latex_header: \usepackage{color}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{textcomp}
#+latex_header: \usepackage{marvosym}
#+latex_header: \usepackage{wasysym}
#+latex_header: \usepackage{latexsym}
#+latex_header: \usepackage{amssymb}
#+latex_header: \usepackage{listings}
#+latex_header: \usepackage{longtable}
#+latex_header: \usepackage[numbers,sort&compress]{natbib}
#+latex_header: \usepackage[linktocpage,
#+latex_header:   pdfstartview=FitH,
#+latex_header:   colorlinks,
#+latex_header:   linkcolor=blue,
#+latex_header:   anchorcolor=blue,
#+latex_header:   citecolor=blue,
#+latex_header:   filecolor=blue,
#+latex_header:   menucolor=blue,
#+latex_header:   urlcolor=blue]{hyperref}
#+latex_header: \tolerance=1000

#+LaTeX_HEADER: \journalname{Topics in Catalysis}

#+LaTeX_HEADER: \author{Spencer D. Miller \and Vladimir V. Pushkarev \and Andrew J. Gellman \and John R. Kitchin}
#+LaTeX_HEADER: \institute{Spencer D. Miller \and Vladimir V. Pushkarev \and Andrew J. Gellman \and John R. Kitchin \at Department of Chemical Engineering, Carnegie Mellon University, Pittsburgh, PA, 15213, USA \\\email{jkitchin@andrew.cmu.edu}}
#+LaTeX_HEADER: \titlerunning{Coverage dependent TPD spectra}


\maketitle

\date{Received: date / Accepted: date}

\begin{abstract}The dissociative adsorption energy of oxygen on Pt(111) is known to be coverage dependent.  Simple Redhead analysis of temperature programmed desorption (TPD) experiments that assumes a coverage independent desorption barrier can lead to errors in estimated properties such as desorption barriers and adsorption energies. A simple correction is to assume a linear coverage dependence of the desorption barrier, but there is usually no formal justification given for that functional form. More advanced TPD analysis methods that are suitable for determining coverage dependent adsorption parameters are limited by their need for large amounts of high quality, low noise data.  We present a method to estimate the functional form of the coverage dependent desorption barrier from density functional theory calculations for use in analysis of TPD spectra. Density functional theory was employed to calculate the coverage dependence of the adsorption energy.  Simulated TPD spectra were then produced by empirically scaling the DFT based adsorption energies utilizing the Br\o{}nstead-Evans-Polyani relationship between adsorption energies and desorption barriers.  The resulting simulated spectra show better agreement with the experimental spectra than spectra predicted using barriers that are either coverage-independent or simply linearly dependent on coverage.  The empirically derived scaling of the desorption barriers for Pt(111) is shown to be useful in predicting the low coverage desorption barriers for oxygen desorption from other metal surfaces, which showed reasonable agreement with the reported experimental values for those other metals.

\keywords{coverage dependence, temperature programmed desorption, density functional theory, late transition metals}
\end{abstract}

* Introduction
Oxygen adsorption on late transition metals is of significant importance in many reaction networks. It is required for oxidation processes, and also occurs at the cathode of fuel cells.   As the coverage of oxygen on the surface changes, so too do adsorption parameters such as the adsorption energy, a trend which has been measured experimentally [[cite:conrad1974,conrad1977,ivanov1976,thiel1979,steininger1982,root1983,canning1984,campbell1985,cornish1990,bare1995,peterlinz1995,wartnaby1996,saliba1998,stuckless1998,zheng2000,jerdev2002,ihm2004,weaver2005,fischerwolfarth2011]] and calculated computationally [[cite:tang2004,getman2008,miller2009,miller2009:molsim,miller2011]]. The origin of this coverage dependence has previously been discussed in terms of an adsorbate-induced, substrate mediated surface $d$-band modification mechanism that correlates the increase in overlap between  adsorbate and metal atomic orbitals at high adsorbate coverages to decreased adsorption bond strength [[cite:miller2009, miller2009:molsim,miller2011]].

While the origin and behavior of  coverage dependence adsorption energies are important, the adsorption energy remains a useful but rather abstract thermodynamic property.  It is difficult to measure directly the adsorption energy of oxygen on a surface.  Two methods for making such measurements experimentally are to determine adsorption energies from equilibrium adsorption isotherms cite:conrad1974:h,conrad1974  or through sophisticated forms of calorimetry cite:wartnaby1996,stuckless1998,ajo2004,fischerwolfarth2011. A more common method for estimating the properties of a reversible adsorption process, such as oxygen adsorption/desorption from transition metals, is through analysis of temperature programmed desorption (TPD).  TPD experiments are conducted by first adsorbing onto the clean metal surface a specified amount of the desired adsorbate at a specified temperature, and then measuring the rate of desorption as the surface is heated in a controlled manner.  The resulting desorption rate versus temperature curve is known as a TPD "spectrum", and the experiment is typically repeated using multiple initial coverages.  The resulting TPD spectra can then be analyzed to determine adsorption properties, such as the desorption barrier, which is often reported as an adsorption energy under the assumption that adsorption is non-activated.

Many oxygen TPD experiments have been performed on the late transition metals, including Rh cite:thiel1979,root1983,peterlinz1995, Ir cite:ivanov1976,cornish1990, Pd cite:conrad1977,zheng2000, Pt cite:steininger1982,jerdev2002,weaver2005, Ag cite:campbell1985,bare1995, and Au cite:canning1984,saliba1998.  The numerous different TPD analysis methods rely on the use of different assumptions, rate equations, or isotherms.  The most common method of analysis used in the experimental TPD studies considered here cite:ivanov1976,conrad1977,thiel1979,root1983,canning1984,campbell1985,cornish1990,bare1995,peterlinz1995,saliba1998,zheng2000  is Redhead analysis cite:redhead1962.  In this analysis method, a coverage independent desorption barrier is assumed, and a desorption order is assumed. Then algebraic equations relating the peak desorption temperature and the desorption barrier are used to estimate the barrier from experimental measurements. Another common method, leading edge analysis cite:Habenschaden1984L147, is not utilized by any of the studies considered, possibly due to low signal to noise ratios in the regions of the spectra where this technique is applied.  A third method, complete analysis, was used in a small number of these studies cite:conrad1977,thiel1979,bare1995  and may be the most accurate of the TPD analysis techniques considered here cite:dejong1990.  The advantages of the leading edge and the complete analysis methods is that, in principle, they yield coverage dependent desorption barriers and pre-exponential factors directly from the experimental data, without the need to postulate the functional form of the coverage dependence. The disadvantage of these two methods is the need for a large amount of high quality data spanning a large coverage range.

In this work, we present an alternative approach to TPD analysis that involves directly integrating the adsorbate mole balance equation with the coverage dependence of the desorption barrier based on DFT calculations. We use DFT calculations to obtain the coverage dependent oxygen adsorption energy, and then use a Br\o{}nstead-Evans-Polyani (BEP) relationship (simple linear scaling) to relate the adsorption energies to desorption barriers. We determine the scaling parameters by using the DFT-derived, coverage dependent desorption barrier to simulate TPD spectra that are then fit to the experimental TPD spectra by adjusting the BEP scaling parameters. We find that this fit to the experimental spectra is superior to those obtained using barriers that are either coverage independent or linearly dependent on coverage. Finally, we show that the scaling is apparently not unique to Pt, as the same scaling parameters reasonably predict the oxygen desorption barriers in the low coverage limit on several other metal surfaces.

* Experimental methods
The TPD experiments were carried out in a custom built stainless steel UHV chamber cite:horvath2002.  The chamber was evacuated by a 260 L/s turbo-molecular pump (Pfeiffer, TMU 260), a 4000 L/s two stage cryopump (CTI-Cryogenics, Cryo-Torr 8), and a 500 (N_2) L/s titanium-sublimation pump (Varian).  The background pressure was $\leq 4 \times 10^{-10}$ mbar and the background gas was composed mostly of H_2 ($m/q$ = 2 ), H_{2}O (18), CO (28) and CO_{2} (44), as determined from the mass spectra.  The chamber was equipped with a quadrupole mass spectrometer (QMS, Ametek Dycor 2000) for TPD, an X-ray photoelectron spectrometer constructed from a hemispherical energy analyzer (VG Microtech, CLAM 2) and a twin Mg/Al anode x-ray source (SPECS, XR50) for XPS, and a three-grid, dual microchannel-plate low energy electron diffraction optics (OCI Vacuum Engineering) for LEED.

A highly polished Pt single crystal (0.99999 purity) disk of 10 mm diameter with (111) face orientation (Monocrystals Co.) was attached to the UHV sample manipulator by spot-welding to two Ta wire posts.  The mounted crystal was resistively heated to 1300 K with a DC current or cooled via a thermal contact with a liquid nitrogen reservoir to 80 K.  The substrate temperature was monitored using a chromel-alumel (Omega) thermocouple that was spot-welded to the edge of the crystal.  A three point calibration procedure, including  submersion at 1 bar atmosphere pressure in boiling liquid nitrogen at 77.4 K and in boiling deionized water at 373.2 K, and an in vacuum calibration at 1150 K using a PYRO MicroOptical pyrometer (Pyrometer Instrument Co.), was performed to achieve \pm 0.5 K accuracy in absolute temperature determination over the full temperature range.  The substrate was first cleaned by repeated cycles of alternating Ar+ ion sputtering and annealing in vacuum at 1100 K until no contamination, except for traces of carbon (C1s), could be detected with XPS.  Subsequently, the substrate was exposed to a large flux of O_{2} (\approx 103 L) at 1 \times 10^{-4} mbar and 700 K and then annealed in vacuum at 1250 K for 1 min.  The heating-cooling rate during the last annealing step was limited to 5 K/sec.  The substrate was considered "clean" if no measurable desorption of CO_{2} was detected with QMS during the annealing step following O_{2} exposure; otherwise, the sputtering-annealing-O_{2} treatment procedure was repeated.  The clean substrate produces a sharp hexagonal LEED pattern and no measurable XPS signal from any element other than Pt.

Ultra high purity grade O_{2} gas (Matheson Tri-Gas) was used in TPD experiments without any additional purification.  The gas exposures were performed by backfilling the UHV chamber using a variable-leak valve (Varian), while simultaneously monitoring the pressure using a  ionization pressure gauge (Varian, UHV-24p).  The ionization gauge was pre-calibrated using an absolute pressure capacitance manometer (MKS Instruments, Baratron 120AA).  All gas exposure values are given in units of Langmuir (1 L = 1.32 \times 10^{-6} mbar \cdot sec), assuming an ionization gauge sensitivity factor of 1.01 (O_{2}).  All reported gas exposures, except for the highest one, were performed at a substrate temperature of 100 K.  Control of the adsorption temperature was essential to achieve linearity of the oxygen coverage versus gas exposure at low exposures ($\le$ 3 L).  O_{2} exposure of the Pt(111) surface at temperatures $<$ 90 K or $>$ 110 K  resulted in lower chemisorbed oxygen coverages, as determined with TPD.  To ensure the surface is saturated by oxygen using low pressure exposure to O_{2}, the substrate was exposed to O_{2} at 7 \times 10^{-5} mbar while the substrate temperature was raised from 100 K to 540 K at 5 K/s and held at 540 K for 200 seconds.

The ionizer of the QMS was enclosed in a tubular, stainless steel shroud with a 7.5 mm diameter circular aperture centered at the end.  After exposure to O_{2} the crystal was positioned 1 mm from the aperture with the substrate surface facing the ionizer.  In this position, the detection of molecules desorbing from the surfaces other than the intended (111) plane was effectively suppressed.  The TPD spectra were recorded at a heating rate of 2 K/s over the 110 K to 1150 K temperature range.  The heating rate was controlled, such that the deviation of the substrate temperature from the set point was less than \pm 0.15 K.  During TPD, the crystal was biased at -70V with respect to the QMS ground to effectively suppress any damage to the overlayer arising from electrons originating in the ionizer.  The QMS was tuned to monitor several mass/charge ratios to detect desorption of O_{2} ($m/q$ = 32) as the molecule of interest, and H_2, CO and CO_{2} as possible contaminants.  If a measurable signal from any of the latter species was detected, the TPD experiment was repeated.

The O_{2} trapping probability on Pt(111) has been measured to be roughly constant between 0.3 and 0.4 for exposures of up to 3L at kinetic energies of 0.035 eV \pm 0.01 eV and substrate temperatures between 90 K and 200 K cite:gross2003. The saturation coverage of O on the Pt(111) surface was assumed to be \theta_O = 0.25 ML based on the observation of a plateau in the integrated area of the TPD peaks with increasing gas exposure, and by comparison  to the shapes of TPD spectra in the literature cite:mudiyanselage2009. Notably, there is no evidence of oxide decomposition peaks in our spectra.

* Computational methods
The DFT calculations were carried out using DACAPO cite:hammer1999 with the Perdew-Wang 91 generalized gradient approximation (GGA) exchange-correlation functional cite:perdew1992 with ultrasoft Vanderbilt pseudopotentials cite:vanderbilt1990.  Four layer slab geometries were used for all calculations with the bottom two layers fixed in bulk positions while the top two layers were allowed to relax.  A 350 eV planewave cutoff was utilized along with a (12 \times 12 \times 1) $k$-point Monkhorst-Pack mesh for the p(1 \times 1) configuration, while all other configurations using meshes of the same density, or as close a density as possible when an exact match was impossible.  The Murnaghan equation of state cite:murnaghan1944  was used to determine the lattice constants, with 4.02 \AA used for the Pt(111) surface.  Only fcc hollow adsorption sites were considered.  Analysis of the coverage dependence of the adsorption energies on Pt, and other late transition metals, has already been performed in detail cite:tang2004,getman2008,miller2011. Coverage is defined as the number of adsorbates per metal atom in the surface, where 1 monolayer (ML) means one adsorbate per surface metal atom, or equivalently one atom per fcc site.

The two-dimensional cluster expansion allows the estimation of adsorption energies to be made rapidly for a very large number of configurations (coverages). The method has been previously described cite:miller2009 and results from that work were used here.

The desorption of oxygen from the Pt(111) surface is a second-order associative desorption process: two adsorbed oxygen atoms must desorb together as a single O_{2} molecule.  The  equation describing the coverage as a function of temperature for second-order desorption, assuming no readsorption, is shown in Equation ref:eq:balance, where $A_d$ is a pre-exponential factor assumed to be 3 \times 10^{12} 1/(ML \cdot s, which was determined by leading edge analysis (shown in the Supporting information). This falls between the limit of a mobile adsorbed state with no rotation $10^{11}$ and an immobile adsorbate ($10^{13}$) cite:Dumesic1993.  \beta is the heating rate (2 K/s for the Pt TPD experiments), \theta is the atomic oxygen coverage, $E_{des}$ is the (possibly coverage-dependent) desorption barrier for oxygen, $R$ is the gas constant, and $T$ is the temperature.  For a known desorption barrier and specified initial coverage, the differential equation can be integrated to solve for $\theta(T)$, which can then be used to produce an estimated TPD spectrum for those conditions.  The desorption barrier can either be constant or a function of coverage.

#+BEGIN_LaTeX
\begin{equation} \label{eq:balance}
\frac{d\theta}{dT} = -\frac{A_d}{\beta}\exp(-E_{des}/RT) \theta^2
\end{equation}
#+END_LaTeX

* Manuscript preparation method
This manuscript was prepared in a manner sufficiently different than standard methods that we feel it warrants discussion. In this work, we have prepared a single document containing all of the raw data, the analysis of the raw data that has led to the figures and conclusions in the manuscript, and the manuscript itself. The document is in plain text format, marked up using org-mode syntax cite:Dominik2010. Org-mode is a lightweight text markup language that enables intermingling of narrative text, data and analysis code in an active document cite:5756277 when viewed in the editor Emacs (http://www.gnu.org/software/emacs/). This approach is known as literate programming and reproducible research cite:v46i03. Notably, files in org-mode syntax can be exported to a variety of other formats including LaTeX, PDF and html. The export can be done selectively to include only portions of the complete document. The published manuscript was exported from this document to create LaTeX source which was submitted to this journal. The Supplementary information file is the document itself, which includes all of the data used in the analysis. All analysis was done using Python (http://python.org), and figures were generated with Matplotlib cite:Hunter:2007. All of these software packages are open-source and freely available.

The advantage of this approach is the complete integration of data analysis, figure generation and manuscript preparation. The final document enables near complete transparency of how the data was analyzed, how the figures were prepared, etc..., because all of the codes used to prepare the data files and figures are embedded directly in the document. The supplemental file is not an afterthought, but rather an integral part of the manuscript preparation. We believe that this approach to manuscript preparation will become increasingly useful in the future as it enhances the communication, distribution and reuse of data and its analysis.

* Results and Discussion
** TPD data and data fitting
The coverage dependent TPD spectra for O_{2} desorption from Pt(111) are shown in Figure ref:fig-tpd1.   These spectra are consistent with previously reported TPD spectra at low coverages cite:allers1996,zhdanov1998, although they lack features at lower temperatures typically associated with the formation of oxide phases that form when exposing Pt(111) to stronger oxidants such as NO cite:mudiyanselage2009 or at substantially higher coverages cite:Parker1989489. The TPD data was first zeroed by subtracting the baseline of the QMS reading from all data points.  The QMS readings, in arbitrary units, were then scaled to a desorption rate in units of ML/K, using a coverage for the TPD spectrum at saturation coverage of 0.25 ML. The saturation coverage was chosen based on the similarity of these spectra to literature reports that identified the saturation limit at 0.25 ML cite:allers1996,zhdanov1998. The initial coverages of the other spectra were determined from their areas (under the curve) relative to that of the spectrum at saturation coverage. All of the analysis is available in the Supporting Information file.   A key feature of these spectra is the growing asymmetry of their leading edges as the initial coverage of adsorbed oxygen increases.  In addition, the shifts in peak temperature with increasing initial coverage become reduced as the initial coverage increases.

#+caption: TPD spectra for O_{2} desorption from Pt(111) after zeroing the baseline and normalization of the area under the largest peak to an initial, saturated oxygen coverage of \theta_O = 0.25 ML. Oxygen exposures ranged from zero to approximately 500 L.  The heating rate was 2 K/sec. \label{fig-tpd1}
#+attr_latex: width=3in
[[./figures/fig1.pdf]]

Second-order desorption is expected for associative desorption of a diatomic molecule such as chemisorbed oxygen desorbing from the Pt surface.  Second-order desorption with a constant desorption barrier results in a characteristic symmetric TPD spectrum that is inconsistent with the experimental data shown in Figure ref:fig-tpd1.  One likely explanation for the asymmetry is that the desorption barrier is coverage dependent; the energy barrier for desorption decreases as the oxygen coverage on the surface increases.  Such coverage dependent desorption energies have been noted in other TPD studies, and are typically modeled with a linear dependence on coverage cite:ivanov1976,thiel1979,root1983.  A linear coverage dependence was unable to accurately fit all of the curves in Figure ref:fig-tpd1. A linearly coverage dependent desorption barrier (with slope and intercept as adjustable parameters) was fit to a low and high coverage spectrum in Figure ref:fig-tpd1 by fitting the numerically simulated TPD spectra using nonlinear least squares fitting. The remaining spectra were simulated using the best fit parameters from the fitted spectrum. The fitted spectra are shown in Figure ref:fig-tpd2, where good agreement at low coverage is observed where fitting was performed, and comparatively poor agreement at the higher coverages. The overall summed squared error (SSE) of this fit was 2.08 $\times 10^{-5}$. A better overall fit is found if a high coverage spectrum is fitted (SSE=6.13 $\times 10^{-6}$), although the low coverage peak temperatures tend to be overestimated. Even with a better fit, there is neither a formal justification for a linear fit, nor a clear way to choose which spectrum to fit. If one fits a linear coverage dependent desorption barrier to each spectrum, a distribution of linear dependences is found (Figure ref:fig-tpd3).

#+caption: Experimental TPD data (black) plotted with second-order simulated TPD spectra obtained using a desorption energy that is linearly dependent on coverage fitted to a) a low coverage peak and b) a high coverage peak. \label{fig-tpd2}
#+attr_latex: width=6in
[[./figures/fig2.pdf]]

#+caption: Desorption barriers versus coverage plotted for each of the fits to the experimental data shown in Figure \ref{fig-tpd2}.  The average desorption barrier is shown as a dashed black line. \label{fig-tpd3}
#+attr_latex: width=3in
[[./figures/fig3.pdf]]

Figure ref:fig-tpd3 illustrates that a range of different linearly coverage dependent desorption barriers may be derived from the experimental spectra, even though there should be only one function describing the coverage dependence of the desorption energy.  There are significant variations in the intercept, and moderate variations in the slope, with increasing intercepts correlating roughly with increasing initial coverage.  This range of desorption barriers could either be evidence of uncertainty in the experimental results, or that a linearly coverage dependent model is not sufficient for capturing the coverage dependence of the desorption barrier.  Next, we use DFT to consider whether the assumption of linear coverage dependence is reasonable.

** Computational approach to coverage dependent adsorption energies
Our computational approach for simulating TPD spectra begins with the Br\o{}nstead-Evans-Polyani (BEP) relationship, which states that the energy of the transition state for a desorption process is linearly related to the adsorption energy of the adsorbate cite:barteau1991,bligaard2004,xu2004.   Xu, Ruban, and Mavrikakis performed a DFT study of the BEP relationship for oxygen dissociation on transition metal surfaces and found a linear relationship held across a wide range of such surfaces cite:xu2004 including the Pt(111) surface. Getman and Schneider have shown that the same relationship applies for coverage dependent oxygen desorption from Pt(111) cite:getman2010.  Thus, we anticipate that the desorption barrier could be proportionally related to the coverage dependent adsorption energy of oxygen on the Pt(111) surface.  This simple linear relationship is shown in Equation ref:eq-bep where \alpha is a proportionality constant and \kappa is a constant offset. In this equation the relevant quantities for temperature programmed desorption are the differential desorption barrier and the differential adsorption energy.

#+BEGIN_LaTeX
\begin{equation} \label{eq-bep}
\Delta E_{des,barrier}=\alpha \cdot \Delta E_{ads} + \kappa
\end{equation}
#+END_LaTeX


To integrate the desorption rate equation with a coverage dependent desorption barrier, it is necessary to have a functional form for the barrier in terms of coverage.  The results from Figure ref:fig-tpd2 were obtained with an assumed linear form of the coverage dependence, but we emphasize again here that there is no formal justification for that choice; it is the next simplest approximation that is not a coverage independent barrier. In conjunction with the BEP relationship, this necessitates possession of an analytical functional form of the adsorption energy in terms of coverage so that Equation ref:eq:balance can be integrated, either analytically or numerically. DFT calculations provide the coverage dependent adsorption energies at discrete coverages, whereas the integration of the desorption rate equation requires a continuous, preferably analytical, function. We now discuss how to derive an effective, analytic functional form for the coverage dependent adsorption energy from a relatively small number of DFT calculations. A key question is which adsorption energies are relevant; some adsorbate configurations and their corresponding adsorption energies may be irrelevant if they are high in energy or unstable. We choose the adsorbate configurations  that are most likely to be thermodynamically relevant, and next discuss how those are identified.

We previously utilized a two-dimensional cluster expansion cite:tang2004 to estimate the adsorption energies for a wide range of configurations of oxygen atoms on Pt(111) in a manner consistent with DFT calculations cite:miller2009.  The prediction error of the cluster expansion was found to be on the same order of magnitude as the convergence uncertainty in the underlying DFT calculations for the VASP data set for oxygen adsorption on Au(111) and Pt(111), lending a significant amount of confidence to the fidelity of the  adsorption energies calculated through the cluster expansion.  When determining the functional form of the adsorption energy versus coverage for use in simulating TPD spectra, the cluster expansion provides a valuable tool for accessing a wider range of configurations than those directly calculated by DFT to ensure no important configurations are missed.  In addition to allowing the coverage dependence of the adsorption energy to be based on a larger set of configurations, it provides the additional advantage of extending the data set into the low coverage regime which is difficult to access directly via DFT because of the computational expense associated with large unit cells.  The low coverage regime is interesting because it is sampled frequently during TPD experiments, and the coverage dependence is expected to decrease nonlinearly as the coverage approaches the dilute limit where interactions between the adsorbate atoms are negligible, even when mediated through the surface metal $d$-bands.

To provide insight into the relative stability of the numerous configurations considered, heats of formation are calculated using heats of adsorption from the cluster expansion as shown in Equation ref:eq-3.  This heat of formation represents the relative stability of a configuration with reference to phase separation into regions of zero coverage and 1 ML coverage.  The convex hull is drawn by linking together those configurations for which no linear combination of configurations exist that are of lower energy.  Those configurations near the convex hull are the most stable with regard to phase separation into regions of clean surface and regions of 1 ML coverage, and represent those that are most thermodynamically relevant and most likely to be populated during TPD experiments.

#+BEGIN_LaTeX
\begin{equation} \label{eq-3}
H_f (\theta)= \theta(E_{ads O}^{average} (\theta)-E_{ads O}^{average }(1\mathrm{ML}))
\end{equation}
#+END_LaTeX


The process of selecting which configurations are thermodynamically relevant, and thus should contribute to determining the functional form of the adsorption energy, was based on how near the configurations were to the convex hull.  At finite temperatures, configurations above the convex hull will be sampled according to the Boltzmann distribution, so that only configurations within a certain energy distance of the convex hull are considered thermodynamically relevant.  The selection of such a region will appear as a band of configurations near the convex hull.  Due to the propagation of errors in Equation ref:eq-3, errors in the heats of formation due to uncertainties in the adsorption energies are proportional to coverage.  Because of this proportionality, the width of the selected region also increases linearly with coverage from zero at the clean surface to 50 meV for a full monolayer, with 50 meV being roughly equivalent to $k_B T$ at 500 K.  The heats of formation of the cluster expansion and DFT calculations are plotted in Figure ref:fig-ce4, in addition to the selected region of the configurations near the convex hull.  The width of the region is shown both above and below the convex hull to guide the eye to seeing which configurations were selected. It is apparent that some of the DFT calculations were not considered in the fit, as some of them are thermodynamically irrelevant under equilibrium conditions.

#+caption: Heats of formation for both the cluster expansion (black dots) and DFT (red squares) results.  The convex hull is drawn as a blue solid line, while the region from which thermodynamically relevant configurations were selected is outlined with dashed blue lines and shaded with light blue.  Those configurations selected are also distinguished as blue triangles. \label{fig-ce4}
#+attr_latex: width=3in
[[./figures/fig4.pdf]]

The average adsorption energies for the selected cluster expansion configurations and those for the DFT calculations are shown together in Figure ref:fig-5.  A constrained fourth-order polynomial least squares fit (Equation ref:eq4) was made to the cluster expansion adsorption energies and a separate fit to the DFT based adsorption energies.  These polynomial fits are constrained to have a slope of zero at zero coverage.  This functional form was selected in order to produce a polynomial that accurately captured the non-linearity of the adsorption energy coverage dependence, while also being consistent with the dilute limit where the slope of the coverage dependence decreases to zero due to the oxygen adsorbate spacing being too great to allow any interaction even through substrate mediated mechanisms. The polynomial form is not critical; other functional forms could be chosen with similar properties. This fitting approach still treats the coverage dependence in a mean field manner, though it  incorporates the nonlinearity of the coverage dependence through the form of the fitting function.

#+BEGIN_LaTeX
\begin{equation} \label{eq4}
E_{ads,fit,DFT}^{average}(\theta)=2.6769 \theta^4 -5.6371 \theta^3 + 4.1292 \theta^2 - 4.1488
\end{equation}
#+END_LaTeX


#+caption: The average adsorption energies for the DFT calculations, and the thermodynamically relevant cluster expansion configurations plotted versus oxygen coverage.  Fourth-order polynomial fits, constrained to have zero slope at zero coverage, are plotted for both data sets.  The fit to the DFT data uses only the lowest energy configuration at each coverage.  Note that the polynomials are nearly overlapping in all but the highest coverages, so the cluster expansion fit is somewhat obscured. \label{fig-5}
#+attr_latex: width=3in
[[./figures/fig5.pdf]]

The selected cluster expansion data is already known to consist of thermodynamically relevant configurations; the same is not true of the DFT data which contains configurations outside the selection window.  Although a similar analysis could be performed to select the most relevant DFT calculations for fitting, we note that there may be an insufficient number of DFT points to properly characterize the ground state hull, which could lead to spurious errors in the selection process. As a result, the polynomial fit to the DFT data incorporates only the lowest energy configuration at each coverage, all of which are close to the ground state convex hull.  The polynomial fit derived from the lowest energy DFT data is very similar to that for the cluster expansion with only a slight offset at moderate coverages. The only significant deviations occur at coverages above those accessible through a TPD experiment due to the formation of oxides.  Surprisingly, in the low coverage limit where DFT calculations are completely absent, the agreement is excellent. This is convenient, because it motivates a method to estimate coverage dependent functions from a small amount of data, where it is not possible to obtain a cluster expansion.

** Relating DFT adsorption energies to desorption barriers

Equation ref:eq4 does not quite provide the necessary adsorption energy for use in Equation ref:eq-bep. For the TPD simulation, we need the differential desorption barrier, which we can derive from the BEP relationship with the differential adsorption energy. Equation ref:eq4 is the average adsorption energy, and it is related to the differential adsorption energy as follows cite:grabow2010:

#+BEGIN_LaTeX
\begin{equation}
E_{ads}^{int}(\theta) = \theta \cdot E^{avg}_{ads}(\theta)
\end{equation}

\begin{equation}\label{eq:Ediff}
E_{ads}^{diff}(\theta) = \frac{dE^{int}_{ads}(\theta)}{d\theta}
\end{equation}
#+END_LaTeX

These quantities are easy to derive from the polynomial fit in ref:eq4. Equation ref:eq:Ediff provides the differential adsorption energy for use with the BEP relationship (Equation ref:eq-bep); however, the linear proportionality (\alpha) and offset (\kappa) parameters remain unknown.   These parameters were empirically fitted using a non-linear least squares approach to minimize the error between simulated TPD spectra and the experimental data shown in Figure ref:fig-tpd1.  Unlike the previous fit to a simple linear function (Figure ref:fig-tpd2), a single coverage dependent desorption barrier function with two parameters was fit to all of the spectra.  The simulated spectra derived for this fit, with \alpha = -0.47 and \kappa = 0.01,  are plotted along with the experimental data in Figure ref:fig6. The summed squared error of this fit over all of the data is 6.17 $\times 10^{-6}. This is comparable to a simple linear fit to a single high coverage spectra (SSE=6.13 $\times 10^{-6}), but the low temperature peaks are fit better with the DFT derived barrier. Furthermore, the fitted equation is based on DFT-derived coverage dependence, rather than an assumed linear form.

#+caption: DFT based and experimental TPD spectra.  The DFT based spectra are derived by integration of the second-order desorption rate equation using a coverage dependent desorption barrier that was empirically fit to experimental spectra, but relies on coverage dependence derived from DFT calculations. \label{fig6}
#+attr_latex: width=3in
[[./figures/fig6.pdf]]

Although the simulated spectra do undergo an empirical fit to the experimental data, they are nonetheless based on a DFT derived coverage dependence that is simply scaled and (slightly) offset.  Agreement between the simulated, empirically fit, TPD spectra and the experimental data is relatively consistent throughout the range of initial coverages, with the best agreement occurring in the moderate coverage range.  As the initial coverage increases, the peak maxima shift to lower temperatures, and the peaks begin to lose symmetry as is captured in the simulated spectra.  It is notable that the primary region of disagreement between the simulated and experimental data is in the leading and trailing edges of the spectra. This is suggestive that the pre-exponential constant may be coverage dependent also, which was not considered in this work. It is possible to produce better agreement at low coverage if the high coverage peaks are neglected in the fitting procedure. That approach could be justified by the formation of oxide structures on the metal surface, where the DFT derived coverage dependent model would clearly break down. However, overall strong agreement was observed when all peaks were included, suggesting that surface oxides were not playing a crucial role for this dataset, and we believe the maximum coverage in this data set is well below the coverage where oxides are known to occur.  Surface oxide chains have been observed by Devarajan, Hinojosa, and Weaver at a coverage of 0.4 ML, and may dominate much of the surface by 0.6 ML cite:devarajan2008. Chemisorbed configurations of 0.5 ML have been previously reported cite:jerdev2002,weaver2005 and may be due  to kinetic limitations cite:Parker1989489 on the formation of oxide structures even if they are thermodynamically favored (effectively locking in the chemisorbed configurations at coverages above those where formation of oxides would be favored).  Getman, Xu and Schneider performed a DFT study of O on Pt (111) cite:getman2008 and found that surface oxide formation was favorable at 0.5 ML by utilizing an atomistic thermodynamics approach.

#+caption: Desorption barriers plotted versus coverage (up to 0.25 ML) derived from analysis of the TPD spectra assuming a linearly coverage-dependent barrier (in blue), with the average of these barriers plotted as a black dashed line, and from the DFT based desorption barrier as a red solid line. \label{fig7}
#+attr_latex: width=3in
[[./figures/fig7.pdf]]

The DFT-derived, empirically fit desorption barrier utilized in the simulation of the TPD spectra in Figure ref:fig6 is plotted in Figure ref:fig7 with the desorption barriers derived from analysis of the TPD spectra using a linear coverage-dependent desorption barrier as originally plotted in Figure ref:fig-tpd3.  The simulated desorption barrier is lower than the average barrier at low coverage, and clearly non-linear in this region up to about 0.1 ML.  It is thus observed that, the linearity of the coverage dependent desorption barrier is generally a reasonable assumption for the range of moderate coverages (0.1 ML $< \theta <$ 0.2 ML), but is not reasonable at the lowest coverages where non-linearity is expected because the adsorbates are at too low a coverage to interact with one another.

The empirical fitting parameters (\alpha and \kappa) are not arbitrary constants.  The proportionality constant \alpha is related to the BEP linear correlation, relating the adsorption energies of oxygen on Pt(111), and other transition metal surfaces, to their desorption barriers.  The offset parameter, \kappa, includes a contribution from the BEP correlation in addition to a further offset that originates in systematic differences such as those that exist between observed and computational values, and even further those that are introduced by different computational techniques, such as differences in the reference oxygen structure such as molecular or atomic oxygen. In this work, these contributions apparently sum to approximately zero. Additional systematic differences are introduced by simplification of the computational technique from the all-electron approach, through the use of the frozen core approximation and ultra-soft pseudopotentials.  Selection of different computational parameters generally preserves the same trend of adsorption energies, while introducing additional offsets.

In the end, these systematic differences, including the offset between computationally and experimentally measured energies, differences between different DFT calculation techniques, and the BEP offset term are lumped together into a single factor, \kappa, whose value was determined empirically by fitting to the TPD data.  The work of  Xu, Ruban, and Mavrikakis showed a single correlation between  the oxygen dissociation barrier and oxygen adsorption energies on a range of transition metals cite:xu2004. As a result, the fitted corrections derived in this work are not necessarily unique to the Pt(111)-O system.  The same BEP relationship applies across other late transition metals, and the corrections are expected to be similar for oxygen desorption from the other late transitional metal surfaces, provided that the methods and parameters used to calculate the adsorption energies are consistent with those used for the Pt(111) calculations.

** Transferability of fitting parameters to other metal systems

To demonstrate that these corrections are systematic in nature, low coverage desorption barriers for other metals were calculated using DFT cite:miller2011 and the same empirical parameters fit to the Pt(111) surface above.  In the case of Pt, the polynomial fit to the cluster expansion data was so similar to the fit directly to the DFT data that we assumed that the polynomial fit to the DFT data for the other metal surfaces was sufficient for the remaining metal surfaces.  The low coverage limit of the adsorption energy was then converted into a low coverage limit for the desorption barrier using the same relationship and empirical constants as used for the Pt(111) surface (Equation ref:eq-bep with \alpha = -0.47 and \kappa = 0.01).

Only oxygen desorption spectra from Pt(111) were experimentally measured in this work.  To compare the desorption barriers derived from the DFT calculations to experimentally measured barriers, it was necessary to draw upon the extensive body of experimental TPD literature available cite:ivanov1976,conrad1977,thiel1979,root1983,canning1984,campbell1985,cornish1990,bare1995,peterlinz1995,saliba1998,zheng2000. Because the experiments were not devised as a single project with the goal of measuring the desorption barrier of chemisorbed oxygen from various (111) surface of late transition metals with a consistent experimental setup and analysis technique, the results are difficult to interpret due to the varied nature of experimental techniques, technology, analysis methodology, and purpose of the experiments.   The goal is to estimate, to the extent possible, the low coverage desorption barrier as best determined by these experiments.  In some cases, the estimation of the desorption barrier was not reported, but the data provided could be utilized to make such an estimate.  At least two experimental data sets were used for the estimation on each metal surface.

In the case of the noble metals (Ag and Au), very similar TPD results are observed in all four data sets cite:canning1984,campbell1985,bare1995,saliba1998 with small peaks like those observed at low coverage on Pt, quickly shifting at even moderate exposures to a shape more closely matching a first-order desorption process.  The p(4 \times 4) LEED pattern observed by Campbell cite:campbell1985 at low coverages of oxygen on Ag is consistent with the formation of surface oxide films, which are likely present for all but the lowest exposure TPD curves.  The resulting oxide-dominated TPD curves were analyzed in that work using the Redhead equation with first-order kinetics and an assumed pre-exponential factor of 10^{15} s^{-1}, resulting in an estimated desorption barrier of 1.73 eV.  Bare, Griffiths, Lennard, and Tang cite:bare1995 performed similar TPD experiments on Ag(111) and found the same basic behavior.  They suggested that two states of adsorbed oxygen exist on the surface, the first existing at very low coverages with no discernable LEED pattern, followed by the formation of the p(4 \times 4) layer at higher coverage which again displays first-order behavior.  This would be consistent with the adsorption of a low order dilute chemisorbed phase followed by the formation of surface oxides.  In this case, the desorption barrier was not directly calculated, but utilizing the measured peak temperatures and initial coverage calculations published in the work, we estimated a desorption barrier of 1.32 eV for the low coverage peaks (which are most likely to be chemisorbed oxygen), assuming second-order kinetics with a pre-exponential factor of 10^{12} ML^{-1}s^{-1}.  The desorption barrier for the higher coverage oxide configurations was not calculated.  Canning, Outka, and Madix cite:canning1984 observed similar characteristic behavior for O desorption from the Au(111) surface, and speculated that oxide formation was occurring due to the high exposures of oxygen provided.  They used a heating rate of 21.5 K/s, which is substantially higher than the 2 K/s rate used in our Pt TPD experiments, and calculated the desorption barrier assuming first-order kinetics with an assumed pre-exponential factor of 10^{13} s^{-1}, finding a desorption barrier of 1.68 eV.  Saliba, Parker, and Koel cite:saliba1998 also performed TPD on the same surface fourteen years later.  While they observed the same behavior as in the prior three cases, they found that their peak temperatures were 100 K lower than those of Canning: they suggested that the discrepancy was a result of the placement of the thermocouple on a tantalum sample holder as opposed to on the sample crystal itself, providing a clear example of the difficulty inherent in comparing experimental results that are not designed for consistency.  Saliba suggested that the shift in peak behavior between low and high exposures was due to the lifting of the herring-bone reconstruction of the Au(111) surface at an oxygen coverage of roughly 0.1 ML.  However, with reported initial coverages as high as 1.2 ML it is likely that surface oxidation, if not bulk oxidation, is present in the high exposure spectra.  Again, first-order kinetics were assumed due to the shape of the high coverage oxide desorption peaks, with an assumed pre-exponential factor of 10^{13} s^{-1}.  Analysis of the desorption barrier found that a linear coverage dependent model fit the data better than a constant desorption barrier, with a low coverage limit of 1.42 eV.  Performing second-order Redhead analysis on only the low coverage spectra, likely representing cases where chemisorbed oxygen is dominant, with the included initial coverage estimates, results in a low coverage chemisorbed desorption barrier of 1.18 eV.

Oxygen dissociates and adsorbs much more readily on the remaining metals (Ir, Rh, Pd) than on the noble metals, which makes it significantly easier to adsorb oxygen on the surface without forming oxides under ultra-high vacuum conditions.  This behavior results in clearly second-order desorption characteristics up to coverages of roughly 0.25 ML and allows for more consistent analysis of the TPD data.  However, even with the greater consistency in analysis, differences in experimental set up, and procedure (such as heating rates which vary from 5 K/s to 80 K/s) still result in significant disagreement and uncertainty in the low coverage desorption barriers.  Ivanov, Boreskov, and Savchenko cite:ivanov1976 studied O_{2} desorption from the Ir(111) surface and determined that the desorption barrier was significantly dependent on the coverage, with a low coverage limit of 2.82 eV.  Cornish and Avery cite:cornish1990 also performed O_{2} TPD on Ir(111) but did not calculate a desorption barrier based on their results.  The heating rate in this case was rapid and wildly varied (40-80 K/s), and no attempt was made to determine the oxygen coverage for different exposures.  Assuming a 0.25 ML saturation coverage, we estimated the initial coverage of the smaller peaks based on their relative areas.  The desorption barrier was calculated using this approach with second-order kinetics and was found to be 2.43 eV.  Zheng and Altman cite:zheng2000 and Conrad, Ertl, Kuppers, and Latta cite:conrad1977 performed O_{2} TPD on the Pd(111) surface.  Utilizing the second-order Redhead analysis with a pre-exponential factor of 10^{13} ML^{-1}s^{-1}, they estimated desorption barriers of 2.18 eV and 2.3 eV, respectively.   Root, Schmidt, and Fisher cite:root1983 performed O_{2} TPD on the Rh (111) surface finding a desorption barrier of 3.69 eV.  On the same surface Peterlinz and Sibener cite:peterlinz1995 analyzed the desorption barrier including coverage dependence and found a low coverage barrier of 2.43 eV and a high coverage barrier of 1.26 eV.

#+caption: A comparison plot between the low coverage desorption barriers as determined by using the empirical corrections in Equation \ref{eq-bep} derived for O adsorption on Pt (111) to the low coverage adsorption energies of Au, Ag, Pd, Rh, and Ir using the same fitting procedure used for Pt, with 95% confidence intervals based on the uncertainty in the polynomial fit and uncertainty in the empirical fit parameters.  The experimental data points are plotted for each metal (Pt only includes the data from this work), with 95% confidence intervals based on a normal distribution. \label{fig8}
#+attr_latex: width=3in
[[./figures/fig8.pdf]]

The set of experimentally derived low coverage barriers allows for the calculation of a 95% confidence interval based on a normal distribution, which provide for some measure of the scope of uncertainty in the real barriers.  These are plotted in Figure ref:fig8 along with the computational barriers derived using the same set of empirical parameters as used for Pt, and the low coverage limit of the polynomial fit to the adsorption energies of each metal.   The 95% confidence intervals for the simulated barriers are based on uncertainty in both fits: first the polynomial fits to the adsorption energies, and secondly the fit of the empirical parameters. The only experimental data for Pt plotted is that from this work, to which the simulated barrier is fit, leading to agreement by design.  In every case other than Au the uncertainty ranges overlap; this is remarkable agreement given the very basic nature of the simulated desorption barrier calculations and the difficulty in pinning down the experimental low coverage desorption barriers.  Although the comparison is not entirely conclusive given the available data, it is strongly suggestive of both a confirmation of the simple BEP relationship and the systematic nature of the empirical corrections.  It appears possible to reproduce the experimental TPD spectra with relatively high accuracy using first principles coverage dependent trends (at least in the regions where chemisorption is dominant). The empirical corrections utilized to reproduce the spectra are not simply convenient fitting factors to render the simulated data similar to the experimental data, but systematic correction factors with well understood origins.

* Conclusions
	A coverage independent desorption barrier was found to be inadequate to model the experimentally observed TPD behavior of O_{2} desorption from the Pt(111) surface.  Fits utilizing an assumed linear coverage dependence were found to be strong, but required unphysically meaningful individual barriers to be fit to each initial coverage.  A DFT based approach that utilized the coverage dependent differential adsorption energy for oxygen on Pt(111) produced a desorption barrier function that was empirically fit to the experimental spectra based on the BEP relationship.  The resulting simulated spectra were in significant agreement with the experimental observations, and the desorption barrier they were based on was in similarly good agreement with the individual linearly coverage dependent barriers from analysis of the experimental data.  The empirical fitting parameters were concluded to be systematic in nature, and non-specific to the Pt(111) surface, by using the same parameters to produce estimated low coverage desorption barriers for other metal surfaces.  These results help illustrate how DFT results can be related to physically observable adsorption properties, and suggest how insights provided by DFT studies can inform understanding of experimentally observed phenomena.  Additionally, the systematic nature of the empirical corrections demonstrates that results from different DFT techniques can be related both to each other and to experimental observations through systematic corrections.

* Acknowledgments
JRK gratefully acknowledges support from the DOE Office of Science Early Career Research Program (DE-SC0004031).


bibliographystyle:spmpsci

bibliography:tpd-scaling.bib
